package com.saiten.model;

import java.util.Date;

/**
 * AnswerDetailFeedback generated by hbm2java.
 */
@SuppressWarnings("serial")
public class AnswerDetailFeedback implements java.io.Serializable {

	/** The answer detail seq. */
	private Integer answerDetailSeq;

	/** The answer info. */
	private AnswerInfo answerInfo;

	/** The answer form num. */
	private String answerFormNum;

	/** The question seq. */
	private Integer questionSeq;

	/** The mark value. */
	private String markValue;

	/** The testsetnum seq. */
	private Integer testsetnumSeq;

	/** The school code. */
	private String schoolCode;

	/** The question num. */
	private Short testsetNum;

	/** The update date. */
	private Date updateDate;

	/** The create date. */
	private Date createDate;

	/**
	 * Instantiates a new answer detail feedback.
	 */
	public AnswerDetailFeedback() {
	}

	/**
	 * Instantiates a new answer detail feedback.
	 *
	 * @param answerInfo
	 *            the answer info
	 * @param answerFormNum
	 *            the answer form num
	 * @param questionSeq
	 *            the question seq
	 * @param markValue
	 *            the mark value
	 * @param testsetnumSeq
	 *            the testsetnum seq
	 * @param schoolCode
	 *            the school code
	 * @param updateDate
	 *            the update date
	 * @param createDate
	 *            the create date
	 */
	public AnswerDetailFeedback(AnswerInfo answerInfo, String answerFormNum, Integer questionSeq, String markValue,
			Integer testsetnumSeq, String schoolCode, Date updateDate, Date createDate) {
		this.answerInfo = answerInfo;
		this.answerFormNum = answerFormNum;
		this.questionSeq = questionSeq;
		this.markValue = markValue;
		this.testsetnumSeq = testsetnumSeq;
		this.schoolCode = schoolCode;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	/**
	 * Gets the answer detail seq.
	 *
	 * @return the answer detail seq
	 */
	public Integer getAnswerDetailSeq() {
		return this.answerDetailSeq;
	}

	/**
	 * Sets the answer detail seq.
	 *
	 * @param answerDetailSeq
	 *            the new answer detail seq
	 */
	public void setAnswerDetailSeq(Integer answerDetailSeq) {
		this.answerDetailSeq = answerDetailSeq;
	}

	/**
	 * Gets the answer info.
	 *
	 * @return the answer info
	 */
	public AnswerInfo getAnswerInfo() {
		return this.answerInfo;
	}

	/**
	 * Sets the answer info.
	 *
	 * @param answerInfo
	 *            the new answer info
	 */
	public void setAnswerInfo(AnswerInfo answerInfo) {
		this.answerInfo = answerInfo;
	}

	/**
	 * Gets the question seq.
	 *
	 * @return the question seq
	 */
	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	/**
	 * Sets the question seq.
	 *
	 * @param questionSeq
	 *            the new question seq
	 */
	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	/**
	 * Gets the mark value.
	 *
	 * @return the mark value
	 */
	public String getMarkValue() {
		return this.markValue;
	}

	/**
	 * Sets the mark value.
	 *
	 * @param markValue
	 *            the new mark value
	 */
	public void setMarkValue(String markValue) {
		this.markValue = markValue;
	}

	/**
	 * Gets the answer form num.
	 *
	 * @return the answer form num
	 */
	public String getAnswerFormNum() {
		return answerFormNum;
	}

	/**
	 * Sets the answer form num.
	 *
	 * @param answerFormNum
	 *            the new answer form num
	 */
	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	/**
	 * Gets the testsetnum seq.
	 *
	 * @return the testsetnum seq
	 */
	public Integer getTestsetnumSeq() {
		return this.testsetnumSeq;
	}

	/**
	 * Sets the testsetnum seq.
	 *
	 * @param testsetnumSeq
	 *            the new testsetnum seq
	 */
	public void setTestsetnumSeq(Integer testsetnumSeq) {
		this.testsetnumSeq = testsetnumSeq;
	}

	/**
	 * Gets the school code.
	 *
	 * @return the school code
	 */
	public String getSchoolCode() {
		return this.schoolCode;
	}

	/**
	 * Sets the school code.
	 *
	 * @param schoolCode
	 *            the new school code
	 */
	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

	/**
	 * Gets the update date.
	 *
	 * @return the update date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Sets the update date.
	 *
	 * @param updateDate
	 *            the new update date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Gets the creates the date.
	 *
	 * @return the creates the date
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Sets the creates the date.
	 *
	 * @param createDate
	 *            the new creates the date
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Gets the testset num.
	 *
	 * @return the testset num
	 */
	public Short getTestsetNum() {
		return testsetNum;
	}

	/**
	 * Sets the testset num.
	 *
	 * @param testsetNum
	 *            the new testset num
	 */
	public void setTestsetNum(Short testsetNum) {
		this.testsetNum = testsetNum;
	}

}
