package com.saiten.model;

import java.util.Date;

/**
 * AnswerDetailObj generated by hbm2java.
 */
@SuppressWarnings("serial")
public class AnswerDetailObj implements java.io.Serializable {

	/** The answer detail seq. */
	private Integer answerDetailSeq;

	/** The answer info. */
	private AnswerInfo answerInfo;

	/** The answer form num. */
	private String answerFormNum;

	/** The question seq. */
	private Integer questionSeq;

	/** The scoring state. */
	private Short scoringState;

	/** The mark value. */
	private String markValue;

	/** The grade seq. */
	private Integer gradeSeq;

	/** The testsetnum seq. */
	private Integer testsetnumSeq;

	/** The update date. */
	private Date updateDate;

	/** The create date. */
	private Date createDate;

	/** The question num. */
	private Short testsetNum;

	/** The grade num. */
	private Integer gradeNum;

	/** The bit value. */
	private Double bitValue;

	/**
	 * Instantiates a new answer detail obj.
	 */
	public AnswerDetailObj() {
	}

	/**
	 * Instantiates a new answer detail obj.
	 *
	 * @param answerInfo
	 *            the answer info
	 * @param answerFormNum
	 *            the answer form num
	 * @param questionSeq
	 *            the question seq
	 * @param scoringState
	 *            the scoring state
	 * @param markValue
	 *            the mark value
	 * @param gradeSeq
	 *            the grade seq
	 * @param testsetnumSeq
	 *            the testsetnum seq
	 * @param updateDate
	 *            the update date
	 * @param createDate
	 *            the create date
	 */
	public AnswerDetailObj(AnswerInfo answerInfo, String answerFormNum, Integer questionSeq, Short scoringState,
			String markValue, Integer gradeSeq, Integer testsetnumSeq, Date updateDate, Date createDate,
			Integer gradeNum, Double bitValue) {
		this.answerInfo = answerInfo;
		this.answerFormNum = answerFormNum;
		this.questionSeq = questionSeq;
		this.scoringState = scoringState;
		this.markValue = markValue;
		this.gradeSeq = gradeSeq;
		this.testsetnumSeq = testsetnumSeq;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.gradeNum = gradeNum;
		this.bitValue = bitValue;
	}

	/**
	 * Gets the answer detail seq.
	 *
	 * @return the answer detail seq
	 */
	public Integer getAnswerDetailSeq() {
		return this.answerDetailSeq;
	}

	/**
	 * Sets the answer detail seq.
	 *
	 * @param answerDetailSeq
	 *            the new answer detail seq
	 */
	public void setAnswerDetailSeq(Integer answerDetailSeq) {
		this.answerDetailSeq = answerDetailSeq;
	}

	/**
	 * Gets the answer info.
	 *
	 * @return the answer info
	 */
	public AnswerInfo getAnswerInfo() {
		return this.answerInfo;
	}

	/**
	 * Sets the answer info.
	 *
	 * @param answerInfo
	 *            the new answer info
	 */
	public void setAnswerInfo(AnswerInfo answerInfo) {
		this.answerInfo = answerInfo;
	}

	/**
	 * Gets the answer form num.
	 *
	 * @return the answer form num
	 */
	public String getAnswerFormNum() {
		return this.answerFormNum;
	}

	/**
	 * Sets the answer form num.
	 *
	 * @param answerFormNum
	 *            the new answer form num
	 */
	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	/**
	 * Gets the question seq.
	 *
	 * @return the question seq
	 */
	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	/**
	 * Sets the question seq.
	 *
	 * @param questionSeq
	 *            the new question seq
	 */
	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	/**
	 * Gets the scoring state.
	 *
	 * @return the scoring state
	 */
	public Short getScoringState() {
		return this.scoringState;
	}

	/**
	 * Sets the scoring state.
	 *
	 * @param scoringState
	 *            the new scoring state
	 */
	public void setScoringState(Short scoringState) {
		this.scoringState = scoringState;
	}

	/**
	 * Gets the mark value.
	 *
	 * @return the mark value
	 */
	public String getMarkValue() {
		return this.markValue;
	}

	/**
	 * Sets the mark value.
	 *
	 * @param markValue
	 *            the new mark value
	 */
	public void setMarkValue(String markValue) {
		this.markValue = markValue;
	}

	/**
	 * Gets the grade seq.
	 *
	 * @return the grade seq
	 */
	public Integer getGradeSeq() {
		return this.gradeSeq;
	}

	/**
	 * Sets the grade seq.
	 *
	 * @param gradeSeq
	 *            the new grade seq
	 */
	public void setGradeSeq(Integer gradeSeq) {
		this.gradeSeq = gradeSeq;
	}

	/**
	 * Gets the testsetnum seq.
	 *
	 * @return the testsetnum seq
	 */
	public Integer getTestsetnumSeq() {
		return this.testsetnumSeq;
	}

	/**
	 * Sets the testsetnum seq.
	 *
	 * @param testsetnumSeq
	 *            the new testsetnum seq
	 */
	public void setTestsetnumSeq(Integer testsetnumSeq) {
		this.testsetnumSeq = testsetnumSeq;
	}

	/**
	 * Gets the update date.
	 *
	 * @return the update date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Sets the update date.
	 *
	 * @param updateDate
	 *            the new update date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Gets the creates the date.
	 *
	 * @return the creates the date
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Sets the creates the date.
	 *
	 * @param createDate
	 *            the new creates the date
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Gets the testset num.
	 *
	 * @return the testset num
	 */
	public Short getTestsetNum() {
		return testsetNum;
	}

	/**
	 * Sets the testset num.
	 *
	 * @param testsetNum
	 *            the new testset num
	 */
	public void setTestsetNum(Short testsetNum) {
		this.testsetNum = testsetNum;
	}

	public Double getBitValue() {
		return bitValue;
	}

	public void setBitValue(Double bitValue) {
		this.bitValue = bitValue;
	}

	public Integer getGradeNum() {
		return gradeNum;
	}

	public void setGradeNum(Integer gradeNum) {
		this.gradeNum = gradeNum;
	}

}
