package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MstCheckPoint generated by hbm2java
 */
public class MstCheckPoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int checkPointSeq;
	private MstQuestion mstQuestion;
	private MstCheckPointGroup mstCheckPointGroup;
	private Short checkPoint;
	private String checkPointDescription;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;

	public MstCheckPoint() {
	}

	public MstCheckPoint(int checkPointSeq) {
		this.checkPointSeq = checkPointSeq;
	}

	public MstCheckPoint(int checkPointSeq, MstQuestion mstQuestion,
			MstCheckPointGroup mstCheckPointGroup, Short checkPoint,
			String checkPointDescription, Character deleteFlag,
			String updatePersonId, Date updateDate, Date createDate) {
		this.checkPointSeq = checkPointSeq;
		this.mstQuestion = mstQuestion;
		this.mstCheckPointGroup = mstCheckPointGroup;
		this.checkPoint = checkPoint;
		this.checkPointDescription = checkPointDescription;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public int getCheckPointSeq() {
		return this.checkPointSeq;
	}

	public void setCheckPointSeq(int checkPointSeq) {
		this.checkPointSeq = checkPointSeq;
	}

	public MstQuestion getMstQuestion() {
		return this.mstQuestion;
	}

	public void setMstQuestion(MstQuestion mstQuestion) {
		this.mstQuestion = mstQuestion;
	}

	public MstCheckPointGroup getMstCheckPointGroup() {
		return this.mstCheckPointGroup;
	}

	public void setMstCheckPointGroup(MstCheckPointGroup mstCheckPointGroup) {
		this.mstCheckPointGroup = mstCheckPointGroup;
	}

	public Short getCheckPoint() {
		return this.checkPoint;
	}

	public void setCheckPoint(Short checkPoint) {
		this.checkPoint = checkPoint;
	}

	public String getCheckPointDescription() {
		return this.checkPointDescription;
	}

	public void setCheckPointDescription(String checkPointDescription) {
		this.checkPointDescription = checkPointDescription;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
