package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstCheckPointGroup generated by hbm2java
 */
public class MstCheckPointGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int checkPointGroupSeq;
	private Integer groupId;
	private Byte groupType;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstCheckPoint> mstCheckPoints = new HashSet<MstCheckPoint>(0);
	private String bgColor;

	public MstCheckPointGroup() {
	}

	public MstCheckPointGroup(int checkPointGroupSeq) {
		this.checkPointGroupSeq = checkPointGroupSeq;
	}

	public MstCheckPointGroup(int checkPointGroupSeq, Integer groupId,
			Byte groupType, Character deleteFlag, String updatePersonId,
			Date updateDate, Date createDate,String bgColor, Set<MstCheckPoint> mstCheckPoints) {
		this.checkPointGroupSeq = checkPointGroupSeq;
		this.groupId = groupId;
		this.groupType = groupType;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstCheckPoints = mstCheckPoints;
		this.bgColor=bgColor;
	}

	public int getCheckPointGroupSeq() {
		return this.checkPointGroupSeq;
	}

	public void setCheckPointGroupSeq(int checkPointGroupSeq) {
		this.checkPointGroupSeq = checkPointGroupSeq;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Byte getGroupType() {
		return this.groupType;
	}

	public void setGroupType(Byte groupType) {
		this.groupType = groupType;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstCheckPoint> getMstCheckPoints() {
		return this.mstCheckPoints;
	}

	public void setMstCheckPoints(Set<MstCheckPoint> mstCheckPoints) {
		this.mstCheckPoints = mstCheckPoints;
	}

	/**
	 * @return the bgColor
	 */
	public String getBgColor() {
		return bgColor;
	}

	/**
	 * @param bgColor
	 *            the bgColor to set
	 */
	public void setBgColor(String bgColor) {
		this.bgColor = bgColor;
	}

}
