package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstEvaluation generated by hbm2java
 */
public class MstEvaluation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int evalSeq;
	private MstQuestionType mstQuestionType;
	private Character csvQuestionType;
	private Character scoreType;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstQuestion> mstQuestions = new HashSet<MstQuestion>(0);

	public MstEvaluation() {
	}

	public MstEvaluation(int evalSeq) {
		this.evalSeq = evalSeq;
	}

	public MstEvaluation(int evalSeq, MstQuestionType mstQuestionType,
			Character csvQuestionType, Character scoreType,
			Character deleteFlag, String updatePersonId, Date updateDate,
			Date createDate, Set<MstQuestion> mstQuestions) {
		this.evalSeq = evalSeq;
		this.mstQuestionType = mstQuestionType;
		this.csvQuestionType = csvQuestionType;
		this.scoreType = scoreType;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstQuestions = mstQuestions;
	}

	public int getEvalSeq() {
		return this.evalSeq;
	}

	public void setEvalSeq(int evalSeq) {
		this.evalSeq = evalSeq;
	}

	public MstQuestionType getMstQuestionType() {
		return this.mstQuestionType;
	}

	public void setMstQuestionType(MstQuestionType mstQuestionType) {
		this.mstQuestionType = mstQuestionType;
	}

	public Character getCsvQuestionType() {
		return this.csvQuestionType;
	}

	public void setCsvQuestionType(Character csvQuestionType) {
		this.csvQuestionType = csvQuestionType;
	}

	public Character getScoreType() {
		return this.scoreType;
	}

	public void setScoreType(Character scoreType) {
		this.scoreType = scoreType;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstQuestion> getMstQuestions() {
		return this.mstQuestions;
	}

	public void setMstQuestions(Set<MstQuestion> mstQuestions) {
		this.mstQuestions = mstQuestions;
	}

}
