package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MstGrade generated by hbm2java
 */
public class MstGrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int gradeSeq;
	private MstGradeResult mstGradeResult;
	private MstQuestion mstQuestion;
	private Double bitValue;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;

	public MstGrade() {
	}

	public MstGrade(int gradeSeq) {
		this.gradeSeq = gradeSeq;
	}

	public MstGrade(int gradeSeq, MstGradeResult mstGradeResult,
			MstQuestion mstQuestion, Double bitValue, Character deleteFlag,
			String updatePersonId, Date updateDate, Date createDate) {
		this.gradeSeq = gradeSeq;
		this.mstGradeResult = mstGradeResult;
		this.mstQuestion = mstQuestion;
		this.bitValue = bitValue;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public int getGradeSeq() {
		return this.gradeSeq;
	}

	public void setGradeSeq(int gradeSeq) {
		this.gradeSeq = gradeSeq;
	}

	public MstGradeResult getMstGradeResult() {
		return this.mstGradeResult;
	}

	public void setMstGradeResult(MstGradeResult mstGradeResult) {
		this.mstGradeResult = mstGradeResult;
	}

	public MstQuestion getMstQuestion() {
		return this.mstQuestion;
	}

	public void setMstQuestion(MstQuestion mstQuestion) {
		this.mstQuestion = mstQuestion;
	}

	public Double getBitValue() {
		return this.bitValue;
	}

	public void setBitValue(Double bitValue) {
		this.bitValue = bitValue;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
