package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstGradeResult generated by hbm2java
 */
public class MstGradeResult implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MstGradeResultId id;
	private String gradeDescription;
	private Character result;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstGrade> mstGrades = new HashSet<MstGrade>(0);

	public MstGradeResult() {
	}

	public MstGradeResult(MstGradeResultId id) {
		this.id = id;
	}

	public MstGradeResult(MstGradeResultId id, String gradeDescription,
			Character result, Character deleteFlag, String updatePersonId,
			Date updateDate, Date createDate, Set<MstGrade> mstGrades) {
		this.id = id;
		this.gradeDescription = gradeDescription;
		this.result = result;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstGrades = mstGrades;
	}

	public MstGradeResultId getId() {
		return this.id;
	}

	public void setId(MstGradeResultId id) {
		this.id = id;
	}

	public String getGradeDescription() {
		return this.gradeDescription;
	}

	public void setGradeDescription(String gradeDescription) {
		this.gradeDescription = gradeDescription;
	}

	public Character getResult() {
		return this.result;
	}

	public void setResult(Character result) {
		this.result = result;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstGrade> getMstGrades() {
		return this.mstGrades;
	}

	public void setMstGrades(Set<MstGrade> mstGrades) {
		this.mstGrades = mstGrades;
	}

}
