package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

/**
 * MstMenuRoleId generated by hbm2java
 */
public class MstMenuRoleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String menuId;
	private byte roleId;

	public MstMenuRoleId() {
	}

	public MstMenuRoleId(String menuId, byte roleId) {
		this.menuId = menuId;
		this.roleId = roleId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public byte getRoleId() {
		return this.roleId;
	}

	public void setRoleId(byte roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstMenuRoleId))
			return false;
		MstMenuRoleId castOther = (MstMenuRoleId) other;

		return ((this.getMenuId() == castOther.getMenuId()) || (this
				.getMenuId() != null && castOther.getMenuId() != null && this
				.getMenuId().equals(castOther.getMenuId())))
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		result = 37 * result + this.getRoleId();
		return result;
	}

}
