package com.saiten.model;

// Generated Dec 1, 2014 12:38:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MstMarkValue generated by hbm2java
 */
@SuppressWarnings("serial")
public class MstMarkValue implements java.io.Serializable {

	private int markValueSeq;
	private Integer questionSeq;
	private Short markValue;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;

	public MstMarkValue() {
	}

	public MstMarkValue(int markValueSeq) {
		this.markValueSeq = markValueSeq;
	}

	public MstMarkValue(int markValueSeq, Integer questionSeq, Short markValue,
			Character deleteFlag, String updatePersonId, Date updateDate,
			Date createDate) {
		this.markValueSeq = markValueSeq;
		this.questionSeq = questionSeq;
		this.markValue = markValue;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public int getMarkValueSeq() {
		return this.markValueSeq;
	}

	public void setMarkValueSeq(int markValueSeq) {
		this.markValueSeq = markValueSeq;
	}

	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	public Short getMarkValue() {
		return this.markValue;
	}

	public void setMarkValue(Short markValue) {
		this.markValue = markValue;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
