package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstQuestionType generated by hbm2java
 */
public class MstQuestionType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private char questionType;
	private String answerScoreTable;
	private String answerScoreHistoryTable;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstEvaluation> mstEvaluations = new HashSet<MstEvaluation>(0);

	public MstQuestionType() {
	}

	public MstQuestionType(char questionType) {
		this.questionType = questionType;
	}

	public MstQuestionType(char questionType, String answerScoreTable,
			String answerScoreHistoryTable, Character deleteFlag,
			String updatePersonId, Date updateDate, Date createDate,
			Set<MstEvaluation> mstEvaluations) {
		this.questionType = questionType;
		this.answerScoreTable = answerScoreTable;
		this.answerScoreHistoryTable = answerScoreHistoryTable;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstEvaluations = mstEvaluations;
	}

	public char getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(char questionType) {
		this.questionType = questionType;
	}

	public String getAnswerScoreTable() {
		return this.answerScoreTable;
	}

	public void setAnswerScoreTable(String answerScoreTable) {
		this.answerScoreTable = answerScoreTable;
	}

	public String getAnswerScoreHistoryTable() {
		return this.answerScoreHistoryTable;
	}

	public void setAnswerScoreHistoryTable(String answerScoreHistoryTable) {
		this.answerScoreHistoryTable = answerScoreHistoryTable;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstEvaluation> getMstEvaluations() {
		return this.mstEvaluations;
	}

	public void setMstEvaluations(Set<MstEvaluation> mstEvaluations) {
		this.mstEvaluations = mstEvaluations;
	}

}
