package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstQuestion generated by hbm2java
 */
public class MstQuestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int questionSeq;
	private MstSubject mstSubject;
	private MstEvaluation mstEvaluation;
	private MstDbInstance mstDbInstance;
	private Short questionNum;
	private String questionContents;
	private Character side;
	private Short imageHeight;
	private Short imageWidth;
	private String manualFileName;
	private String questionFileName;
	private Short objectiveMax;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private String attribute1;
	private Set<MstScorerQuestion> mstScorerQuestions = new HashSet<MstScorerQuestion>(
			0);
	private Set<MstCheckPoint> mstCheckPoints = new HashSet<MstCheckPoint>(0);
	private Set<MstPendingCategory> mstPendingCategories = new HashSet<MstPendingCategory>(
			0);
	private Set<MstGrade> mstGrades = new HashSet<MstGrade>(0);

	public MstQuestion() {
	}

	public MstQuestion(int questionSeq) {
		this.questionSeq = questionSeq;
	}

	public MstQuestion(int questionSeq, MstSubject mstSubject,
			MstEvaluation mstEvaluation, MstDbInstance mstDbInstance,
			Short questionNum, String questionContents, Character side,
			Short imageHeight, Short imageWidth, String manualFileName,
			String questionFileName, Short objectiveMax, Character deleteFlag,
			String updatePersonId, Date updateDate, Date createDate,
			Set<MstScorerQuestion> mstScorerQuestions,
			Set<MstCheckPoint> mstCheckPoints,
			Set<MstPendingCategory> mstPendingCategories,
			Set<MstGrade> mstGrades, String attribute1) {
		this.questionSeq = questionSeq;
		this.mstSubject = mstSubject;
		this.mstEvaluation = mstEvaluation;
		this.mstDbInstance = mstDbInstance;
		this.questionNum = questionNum;
		this.questionContents = questionContents;
		this.side = side;
		this.imageHeight = imageHeight;
		this.imageWidth = imageWidth;
		this.manualFileName = manualFileName;
		this.questionFileName = questionFileName;
		this.objectiveMax = objectiveMax;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstScorerQuestions = mstScorerQuestions;
		this.mstCheckPoints = mstCheckPoints;
		this.mstPendingCategories = mstPendingCategories;
		this.mstGrades = mstGrades;
		this.attribute1 = attribute1;
	}

	public int getQuestionSeq() {
		return this.questionSeq;
	}

	public void setQuestionSeq(int questionSeq) {
		this.questionSeq = questionSeq;
	}

	public MstSubject getMstSubject() {
		return this.mstSubject;
	}

	public void setMstSubject(MstSubject mstSubject) {
		this.mstSubject = mstSubject;
	}

	public MstEvaluation getMstEvaluation() {
		return this.mstEvaluation;
	}

	public void setMstEvaluation(MstEvaluation mstEvaluation) {
		this.mstEvaluation = mstEvaluation;
	}

	public MstDbInstance getMstDbInstance() {
		return this.mstDbInstance;
	}

	public void setMstDbInstance(MstDbInstance mstDbInstance) {
		this.mstDbInstance = mstDbInstance;
	}

	public Short getQuestionNum() {
		return this.questionNum;
	}

	public void setQuestionNum(Short questionNum) {
		this.questionNum = questionNum;
	}

	public String getQuestionContents() {
		return this.questionContents;
	}

	public void setQuestionContents(String questionContents) {
		this.questionContents = questionContents;
	}

	public Character getSide() {
		return this.side;
	}

	public void setSide(Character side) {
		this.side = side;
	}

	public Short getImageHeight() {
		return this.imageHeight;
	}

	public void setImageHeight(Short imageHeight) {
		this.imageHeight = imageHeight;
	}

	public Short getImageWidth() {
		return this.imageWidth;
	}

	public void setImageWidth(Short imageWidth) {
		this.imageWidth = imageWidth;
	}

	public String getManualFileName() {
		return this.manualFileName;
	}

	public void setManualFileName(String manualFileName) {
		this.manualFileName = manualFileName;
	}

	public String getQuestionFileName() {
		return this.questionFileName;
	}

	public void setQuestionFileName(String questionFileName) {
		this.questionFileName = questionFileName;
	}

	public Short getObjectiveMax() {
		return this.objectiveMax;
	}

	public void setObjectiveMax(Short objectiveMax) {
		this.objectiveMax = objectiveMax;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstScorerQuestion> getMstScorerQuestions() {
		return this.mstScorerQuestions;
	}

	public void setMstScorerQuestions(Set<MstScorerQuestion> mstScorerQuestions) {
		this.mstScorerQuestions = mstScorerQuestions;
	}

	public Set<MstCheckPoint> getMstCheckPoints() {
		return this.mstCheckPoints;
	}

	public void setMstCheckPoints(Set<MstCheckPoint> mstCheckPoints) {
		this.mstCheckPoints = mstCheckPoints;
	}

	public Set<MstPendingCategory> getMstPendingCategories() {
		return this.mstPendingCategories;
	}

	public void setMstPendingCategories(
			Set<MstPendingCategory> mstPendingCategories) {
		this.mstPendingCategories = mstPendingCategories;
	}

	public Set<MstGrade> getMstGrades() {
		return this.mstGrades;
	}

	public void setMstGrades(Set<MstGrade> mstGrades) {
		this.mstGrades = mstGrades;
	}

	public String getAttribute1() {
		return attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

}
