package com.saiten.model;
// Generated Dec 12, 2012 12:02:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstSubject generated by hbm2java
 */
public class MstSubject  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String subjectCode;
     private String schoolType;
     private String subjectShortName;
     private String subjectName;
     private Character scoreFlag;
     private Character docFlag;
     private Character deleteFlag;
     private String updatePersonId;
     private Date updateDate;
     private Date createDate;
     private Set<MstQuestion> mstQuestions = new HashSet<MstQuestion>(0);

    public MstSubject() {
    }

	
    public MstSubject(String subjectCode) {
        this.subjectCode = subjectCode;
    }
    public MstSubject(String subjectCode, String schoolType, String subjectShortName, String subjectName, Character scoreFlag, Character docFlag, Character deleteFlag, String updatePersonId, Date updateDate, Date createDate, Set<MstQuestion> mstQuestions) {
       this.subjectCode = subjectCode;
       this.schoolType = schoolType;
       this.subjectShortName = subjectShortName;
       this.subjectName = subjectName;
       this.scoreFlag = scoreFlag;
       this.docFlag = docFlag;
       this.deleteFlag = deleteFlag;
       this.updatePersonId = updatePersonId;
       this.updateDate = updateDate;
       this.createDate = createDate;
       this.mstQuestions = mstQuestions;
    }
   
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }
    public String getSchoolType() {
        return this.schoolType;
    }
    
    public void setSchoolType(String schoolType) {
        this.schoolType = schoolType;
    }
    public String getSubjectShortName() {
        return this.subjectShortName;
    }
    
    public void setSubjectShortName(String subjectShortName) {
        this.subjectShortName = subjectShortName;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Character getScoreFlag() {
        return this.scoreFlag;
    }
    
    public void setScoreFlag(Character scoreFlag) {
        this.scoreFlag = scoreFlag;
    }
    public Character getDocFlag() {
        return this.docFlag;
    }
    
    public void setDocFlag(Character docFlag) {
        this.docFlag = docFlag;
    }
    public Character getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(Character deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
    public String getUpdatePersonId() {
        return this.updatePersonId;
    }
    
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Set<MstQuestion> getMstQuestions() {
        return this.mstQuestions;
    }
    
    public void setMstQuestions(Set<MstQuestion> mstQuestions) {
        this.mstQuestions = mstQuestions;
    }




}


