package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MstScorerQuestion generated by hbm2java
 */
public class MstScorerQuestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MstScorerQuestionId id;
	private MstScorer mstScorer;
	private MstQuestion mstQuestion;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;

	public MstScorerQuestion() {
	}

	public MstScorerQuestion(MstScorerQuestionId id, MstScorer mstScorer,
			MstQuestion mstQuestion) {
		this.id = id;
		this.mstScorer = mstScorer;
		this.mstQuestion = mstQuestion;
	}

	public MstScorerQuestion(MstScorerQuestionId id, MstScorer mstScorer,
			MstQuestion mstQuestion, Character deleteFlag,
			String updatePersonId, Date updateDate, Date createDate) {
		this.id = id;
		this.mstScorer = mstScorer;
		this.mstQuestion = mstQuestion;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public MstScorerQuestionId getId() {
		return this.id;
	}

	public void setId(MstScorerQuestionId id) {
		this.id = id;
	}

	public MstScorer getMstScorer() {
		return this.mstScorer;
	}

	public void setMstScorer(MstScorer mstScorer) {
		this.mstScorer = mstScorer;
	}

	public MstQuestion getMstQuestion() {
		return this.mstQuestion;
	}

	public void setMstQuestion(MstQuestion mstQuestion) {
		this.mstQuestion = mstQuestion;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
