package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstScorerRole generated by hbm2java
 */
public class MstScorerRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte roleId;
	private String roleDescription;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstScorer> mstScorers = new HashSet<MstScorer>(0);
	private Set<MstMenuRole> mstMenuRoles = new HashSet<MstMenuRole>(0);

	public MstScorerRole() {
	}

	public MstScorerRole(byte roleId) {
		this.roleId = roleId;
	}

	public MstScorerRole(byte roleId, String roleDescription,
			Character deleteFlag, String updatePersonId, Date updateDate,
			Date createDate, Set<MstScorer> mstScorers,
			Set<MstMenuRole> mstMenuRoles) {
		this.roleId = roleId;
		this.roleDescription = roleDescription;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstScorers = mstScorers;
		this.mstMenuRoles = mstMenuRoles;
	}

	public byte getRoleId() {
		return this.roleId;
	}

	public void setRoleId(byte roleId) {
		this.roleId = roleId;
	}

	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstScorer> getMstScorers() {
		return this.mstScorers;
	}

	public void setMstScorers(Set<MstScorer> mstScorers) {
		this.mstScorers = mstScorers;
	}

	public Set<MstMenuRole> getMstMenuRoles() {
		return this.mstMenuRoles;
	}

	public void setMstMenuRoles(Set<MstMenuRole> mstMenuRoles) {
		this.mstMenuRoles = mstMenuRoles;
	}

}
