package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MstSamplingEventCond generated by hbm2java
 */
public class MstSamplingEventCond implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MstSamplingEventCondId id;
	private MstScoringEventList mstScoringEventList;
	private Character defaultValue;
	private Integer displayIndex;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;

	public MstSamplingEventCond() {
	}

	public MstSamplingEventCond(MstSamplingEventCondId id,
			MstScoringEventList mstScoringEventList) {
		this.id = id;
		this.mstScoringEventList = mstScoringEventList;
	}

	public MstSamplingEventCond(MstSamplingEventCondId id,
			MstScoringEventList mstScoringEventList, Character defaultValue,
			Integer displayIndex, Character deleteFlag, String updatePersonId,
			Date updateDate, Date createDate) {
		this.id = id;
		this.mstScoringEventList = mstScoringEventList;
		this.defaultValue = defaultValue;
		this.displayIndex = displayIndex;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public MstSamplingEventCondId getId() {
		return this.id;
	}

	public void setId(MstSamplingEventCondId id) {
		this.id = id;
	}

	public MstScoringEventList getMstScoringEventList() {
		return this.mstScoringEventList;
	}

	public void setMstScoringEventList(MstScoringEventList mstScoringEventList) {
		this.mstScoringEventList = mstScoringEventList;
	}

	public Character getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(Character defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Integer getDisplayIndex() {
		return this.displayIndex;
	}

	public void setDisplayIndex(Integer displayIndex) {
		this.displayIndex = displayIndex;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
