package com.saiten.model;
// Generated Dec 12, 2012 12:02:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MstSchool generated by hbm2java
 */
public class MstSchool  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String schoolCode;
     private String schoolType;
     private String schoolName;
     private Character deleteFlag;
     private String updatePersonId;
     private Date updateDate;
     private Date createDate;

    public MstSchool() {
    }

	
    public MstSchool(String schoolCode) {
        this.schoolCode = schoolCode;
    }
    public MstSchool(String schoolCode, String schoolType, String schoolName, Character deleteFlag, String updatePersonId, Date updateDate, Date createDate) {
       this.schoolCode = schoolCode;
       this.schoolType = schoolType;
       this.schoolName = schoolName;
       this.deleteFlag = deleteFlag;
       this.updatePersonId = updatePersonId;
       this.updateDate = updateDate;
       this.createDate = createDate;
    }
   
    public String getSchoolCode() {
        return this.schoolCode;
    }
    
    public void setSchoolCode(String schoolCode) {
        this.schoolCode = schoolCode;
    }
    public String getSchoolType() {
        return this.schoolType;
    }
    
    public void setSchoolType(String schoolType) {
        this.schoolType = schoolType;
    }
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }
    public Character getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(Character deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
    public String getUpdatePersonId() {
        return this.updatePersonId;
    }
    
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


