package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstScoringEventList generated by hbm2java
 */
public class MstScoringEventList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short eventId;
	private String eventName;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstSamplingEventCond> mstSamplingEventConds = new HashSet<MstSamplingEventCond>(
			0);

	public MstScoringEventList() {
	}

	public MstScoringEventList(short eventId) {
		this.eventId = eventId;
	}

	public MstScoringEventList(short eventId, String eventName,
			Character deleteFlag, String updatePersonId, Date updateDate,
			Date createDate, Set<MstSamplingEventCond> mstSamplingEventConds) {
		this.eventId = eventId;
		this.eventName = eventName;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstSamplingEventConds = mstSamplingEventConds;
	}

	public short getEventId() {
		return this.eventId;
	}

	public void setEventId(short eventId) {
		this.eventId = eventId;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstSamplingEventCond> getMstSamplingEventConds() {
		return this.mstSamplingEventConds;
	}

	public void setMstSamplingEventConds(
			Set<MstSamplingEventCond> mstSamplingEventConds) {
		this.mstSamplingEventConds = mstSamplingEventConds;
	}

}
