package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstScorer generated by hbm2java
 */
public class MstScorer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String scorerId;
	private MstScorerRole mstScorerRole;
	private String password;
	private String scorerName;
	private Character noDbUpdate;
	private Character deleteFlag;
	private String updatePersonId;
	private Date updateDate;
	private Date createDate;
	private Set<MstScorerQuestion> mstScorerQuestions = new HashSet<MstScorerQuestion>(
			0);

	public MstScorer() {
	}

	public MstScorer(String scorerId, MstScorerRole mstScorerRole) {
		this.scorerId = scorerId;
		this.mstScorerRole = mstScorerRole;
	}

	public MstScorer(String scorerId, MstScorerRole mstScorerRole,
			String password, String scorerName, Character noDbUpdate,
			Character deleteFlag, String updatePersonId, Date updateDate,
			Date createDate, Set<MstScorerQuestion> mstScorerQuestions) {
		this.scorerId = scorerId;
		this.mstScorerRole = mstScorerRole;
		this.password = password;
		this.scorerName = scorerName;
		this.noDbUpdate = noDbUpdate;
		this.deleteFlag = deleteFlag;
		this.updatePersonId = updatePersonId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.mstScorerQuestions = mstScorerQuestions;
	}

	public String getScorerId() {
		return this.scorerId;
	}

	public void setScorerId(String scorerId) {
		this.scorerId = scorerId;
	}

	public MstScorerRole getMstScorerRole() {
		return this.mstScorerRole;
	}

	public void setMstScorerRole(MstScorerRole mstScorerRole) {
		this.mstScorerRole = mstScorerRole;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getScorerName() {
		return this.scorerName;
	}

	public void setScorerName(String scorerName) {
		this.scorerName = scorerName;
	}

	public Character getNoDbUpdate() {
		return this.noDbUpdate;
	}

	public void setNoDbUpdate(Character noDbUpdate) {
		this.noDbUpdate = noDbUpdate;
	}

	public Character getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Character deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<MstScorerQuestion> getMstScorerQuestions() {
		return this.mstScorerQuestions;
	}

	public void setMstScorerQuestions(Set<MstScorerQuestion> mstScorerQuestions) {
		this.mstScorerQuestions = mstScorerQuestions;
	}

}
