package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

/**
 * MstSamplingStateCondId generated by hbm2java
 */
public class MstSamplingStateCondId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String screenId;
	private short scoringState;

	public MstSamplingStateCondId() {
	}

	public MstSamplingStateCondId(String screenId, short scoringState) {
		this.screenId = screenId;
		this.scoringState = scoringState;
	}

	public String getScreenId() {
		return this.screenId;
	}

	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	public short getScoringState() {
		return this.scoringState;
	}

	public void setScoringState(short scoringState) {
		this.scoringState = scoringState;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstSamplingStateCondId))
			return false;
		MstSamplingStateCondId castOther = (MstSamplingStateCondId) other;

		return ((this.getScreenId() == castOther.getScreenId()) || (this
				.getScreenId() != null && castOther.getScreenId() != null && this
				.getScreenId().equals(castOther.getScreenId())))
				&& (this.getScoringState() == castOther.getScoringState());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getScreenId() == null ? 0 : this.getScreenId().hashCode());
		result = 37 * result + this.getScoringState();
		return result;
	}

}
