package com.saiten.model;

// Generated Dec 3, 2012 11:19:29 AM by Hibernate Tools 3.2.1.GA

/**
 * MstSamplingEventCondId generated by hbm2java
 */
public class MstSamplingEventCondId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String screenId;
	private short eventId;

	public MstSamplingEventCondId() {
	}

	public MstSamplingEventCondId(String screenId, short eventId) {
		this.screenId = screenId;
		this.eventId = eventId;
	}

	public String getScreenId() {
		return this.screenId;
	}

	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	public short getEventId() {
		return this.eventId;
	}

	public void setEventId(short eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstSamplingEventCondId))
			return false;
		MstSamplingEventCondId castOther = (MstSamplingEventCondId) other;

		return ((this.getScreenId() == castOther.getScreenId()) || (this
				.getScreenId() != null && castOther.getScreenId() != null && this
				.getScreenId().equals(castOther.getScreenId())))
				&& (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getScreenId() == null ? 0 : this.getScreenId().hashCode());
		result = 37 * result + this.getEventId();
		return result;
	}

}
