package com.saiten.model;

// Generated 18 Mar, 2015 10:24:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranLookAfterwards generated by hbm2java
 */
public class TranLookAfterwards implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer lookAftSeq;
	private Integer answerSeq;
	private String updatePersonId;
	private Character lookAftFlag;
	private String resolvedBy;
	private Character resolvedFlag;
	private String comment;
	private Date createDate;
	private Date updateDate;

	public TranLookAfterwards() {
	}

	public TranLookAfterwards(Integer answerSeq, String updatePersonId,
			Character lookAftFlag, String comment, Date createDate,
			Date updateDate) {
		this.answerSeq = answerSeq;
		this.updatePersonId = updatePersonId;
		this.lookAftFlag = lookAftFlag;
		this.comment = comment;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getLookAftSeq() {
		return this.lookAftSeq;
	}

	public void setLookAftSeq(Integer lookAftSeq) {
		this.lookAftSeq = lookAftSeq;
	}

	public Integer getAnswerSeq() {
		return this.answerSeq;
	}

	public void setAnswerSeq(Integer answerSeq) {
		this.answerSeq = answerSeq;
	}

	public String getUpdatePersonId() {
		return this.updatePersonId;
	}

	public void setUpdatePersonId(String updatePersonId) {
		this.updatePersonId = updatePersonId;
	}

	public Character getLookAftFlag() {
		return this.lookAftFlag;
	}

	public void setLookAftFlag(Character lookAftFlag) {
		this.lookAftFlag = lookAftFlag;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * @return the resolvedBy
	 */
	public String getResolvedBy() {
		return resolvedBy;
	}

	/**
	 * @param resolvedBy the resolvedBy to set
	 */
	public void setResolvedBy(String resolvedBy) {
		this.resolvedBy = resolvedBy;
	}

	/**
	 * @return the resolvedFlag
	 */
	public Character getResolvedFlag() {
		return resolvedFlag;
	}

	/**
	 * @param resolvedFlag the resolvedFlag to set
	 */
	public void setResolvedFlag(Character resolvedFlag) {
		this.resolvedFlag = resolvedFlag;
	}
	
	
}
