package com.saiten.model;

// Generated Jul 1, 2014 11:56:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranAnswerForm generated by hbm2java
 */
public class TranAnswerForm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TranAnswerFormId id;
	private String classNum;
	private Character answerPaperType;
	private Character gender;
	private Character summaryFlag;
	private Date updateDate;
	private Date createDate;
	private String schoolComment;

	public TranAnswerForm() {
	}

	public TranAnswerForm(TranAnswerFormId id, String classNum) {
		this.id = id;
		this.classNum = classNum;
	}

	public TranAnswerForm(TranAnswerFormId id, String classNum,
			Character answerPaperType, Character gender, Character summaryFlag,
			Date updateDate, Date createDate, String schoolComment) {
		this.id = id;
		this.classNum = classNum;
		this.answerPaperType = answerPaperType;
		this.gender = gender;
		this.summaryFlag = summaryFlag;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.schoolComment = schoolComment;
	}

	public TranAnswerFormId getId() {
		return this.id;
	}

	public void setId(TranAnswerFormId id) {
		this.id = id;
	}

	public String getClassNum() {
		return this.classNum;
	}

	public void setClassNum(String classNum) {
		this.classNum = classNum;
	}

	public Character getAnswerPaperType() {
		return this.answerPaperType;
	}

	public void setAnswerPaperType(Character answerPaperType) {
		this.answerPaperType = answerPaperType;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Character getSummaryFlag() {
		return this.summaryFlag;
	}

	public void setSummaryFlag(Character summaryFlag) {
		this.summaryFlag = summaryFlag;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getSchoolComment() {
		return this.schoolComment;
	}

	public void setSchoolComment(String schoolComment) {
		this.schoolComment = schoolComment;
	}

}
