// default package
// Generated 12 Dec, 2018 11:51:10 AM by Hibernate Tools 5.2.10.Final
package com.saiten.model;
/**
 * TranScorePercentage generated by hbm2java
 */
public class TranScorePercentage implements java.io.Serializable {

	private TranScorePercentageId id;
	private int objPercentage;
	private int shortBatchPercentage;
	private int shortScreenPercentage;
	private int shortPercentage;
	private int longPercentage;
	private int totalPercentage;

	public TranScorePercentage() {
	}

	public TranScorePercentage(TranScorePercentageId id, int objPercentage, int shortBatchPercentage,
			int shortScreenPercentage, int shortPercentage, int longPercentage, int totalPercentage) {
		this.id = id;
		this.objPercentage = objPercentage;
		this.shortBatchPercentage = shortBatchPercentage;
		this.shortScreenPercentage = shortScreenPercentage;
		this.shortPercentage = shortPercentage;
		this.longPercentage = longPercentage;
		this.totalPercentage = totalPercentage;
	}

	public TranScorePercentageId getId() {
		return this.id;
	}

	public void setId(TranScorePercentageId id) {
		this.id = id;
	}

	public int getObjPercentage() {
		return this.objPercentage;
	}

	public void setObjPercentage(int objPercentage) {
		this.objPercentage = objPercentage;
	}

	public int getShortBatchPercentage() {
		return this.shortBatchPercentage;
	}

	public void setShortBatchPercentage(int shortBatchPercentage) {
		this.shortBatchPercentage = shortBatchPercentage;
	}

	public int getShortScreenPercentage() {
		return this.shortScreenPercentage;
	}

	public void setShortScreenPercentage(int shortScreenPercentage) {
		this.shortScreenPercentage = shortScreenPercentage;
	}

	public int getShortPercentage() {
		return this.shortPercentage;
	}

	public void setShortPercentage(int shortPercentage) {
		this.shortPercentage = shortPercentage;
	}

	public int getLongPercentage() {
		return this.longPercentage;
	}

	public void setLongPercentage(int longPercentage) {
		this.longPercentage = longPercentage;
	}

	public int getTotalPercentage() {
		return this.totalPercentage;
	}

	public void setTotalPercentage(int totalPercentage) {
		this.totalPercentage = totalPercentage;
	}

}
