package com.saiten.model;

// Generated 1 Jan, 2015 10:15:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranScorerSessionInfo generated by hbm2java
 */
public class TranScorerSessionInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String scorerId;
	private MstQuestion mstQuestion;
	private String answerFormNum;
	private String subjectCode;
	private Date createDate;
	private Date updateDate;

	public TranScorerSessionInfo() {
	}

	public TranScorerSessionInfo(String scorerId) {
		this.scorerId = scorerId;
	}

	public TranScorerSessionInfo(String scorerId, MstQuestion mstQuestion,
			String answerFormNum, String subjectCode, Date createDate,
			Date updateDate) {
		this.scorerId = scorerId;
		this.mstQuestion = mstQuestion;
		this.answerFormNum = answerFormNum;
		this.subjectCode = subjectCode;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public String getScorerId() {
		return this.scorerId;
	}

	public void setScorerId(String scorerId) {
		this.scorerId = scorerId;
	}

	public MstQuestion getMstQuestion() {
		return this.mstQuestion;
	}

	public void setMstQuestion(MstQuestion mstQuestion) {
		this.mstQuestion = mstQuestion;
	}

	public String getAnswerFormNum() {
		return this.answerFormNum;
	}

	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
