package com.saiten.model;

// Generated 1 Jan, 2015 10:15:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranScorerAccessLog generated by hbm2java
 */
public class TranScorerAccessLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private MstScorer mstScorer;
	private Date loginTime;
	private Date logoutTime;
	private String status;

	public TranScorerAccessLog() {
	}

	public TranScorerAccessLog(MstScorer mstScorer, Date loginTime) {
		this.mstScorer = mstScorer;
		this.loginTime = loginTime;
	}

	public TranScorerAccessLog(MstScorer mstScorer, Date loginTime,
			Date logoutTime, String status) {
		this.mstScorer = mstScorer;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MstScorer getMstScorer() {
		return this.mstScorer;
	}

	public void setMstScorer(MstScorer mstScorer) {
		this.mstScorer = mstScorer;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
