package com.saiten.model;

// Generated 17 Jun, 2016 10:47:02 AM by Hibernate Tools 3.4.0.CR1

/**
 * TranObjScorePercentage generated by hbm2java
 */
public class TranObjScorePercentage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TranObjScorePercentageId id;
	private int resultPercentage;

	public TranObjScorePercentage() {
	}

	public TranObjScorePercentage(TranObjScorePercentageId id,
			int resultPercentage) {
		this.id = id;
		this.resultPercentage = resultPercentage;
	}

	public TranObjScorePercentageId getId() {
		return this.id;
	}

	public void setId(TranObjScorePercentageId id) {
		this.id = id;
	}

	public int getResultPercentage() {
		return this.resultPercentage;
	}

	public void setResultPercentage(int resultPercentage) {
		this.resultPercentage = resultPercentage;
	}

}
