package com.saiten.model;

// Generated Jul 1, 2014 11:56:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranObjScore generated by hbm2java
 */
public class TranObjScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer answerSeq;
	private String answerFormNum;
	private Integer questionSeq;
	private Short scoringState;
	private String markValue;
	private Integer gradeSeq;
	private Date updateDate;
	private Date createDate;

	public TranObjScore() {
	}

	public TranObjScore(String answerFormNum, Integer questionSeq,
			Short scoringState, String markValue, Integer gradeSeq,
			Date updateDate, Date createDate) {
		this.answerFormNum = answerFormNum;
		this.questionSeq = questionSeq;
		this.scoringState = scoringState;
		this.markValue = markValue;
		this.gradeSeq = gradeSeq;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public Integer getAnswerSeq() {
		return this.answerSeq;
	}

	public void setAnswerSeq(Integer answerSeq) {
		this.answerSeq = answerSeq;
	}

	public String getAnswerFormNum() {
		return this.answerFormNum;
	}

	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	public Short getScoringState() {
		return this.scoringState;
	}

	public void setScoringState(Short scoringState) {
		this.scoringState = scoringState;
	}

	public String getMarkValue() {
		return this.markValue;
	}

	public void setMarkValue(String markValue) {
		this.markValue = markValue;
	}

	public Integer getGradeSeq() {
		return this.gradeSeq;
	}

	public void setGradeSeq(Integer gradeSeq) {
		this.gradeSeq = gradeSeq;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
