package com.saiten.model;

// Generated Jul 1, 2014 11:56:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranFeedbackForm generated by hbm2java
 */
public class TranFeedbackForm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer answerSeq;
	private String answerFormNum;
	private Integer questionSeq;
	private String markValue;
	private Date updateDate;
	private Date createDate;
	private String schoolCode;

	public TranFeedbackForm() {
	}

	public TranFeedbackForm(String answerFormNum, String schoolCode) {
		this.answerFormNum = answerFormNum;
		this.schoolCode = schoolCode;
	}

	public TranFeedbackForm(String answerFormNum, Integer questionSeq,
			String markValue, Date updateDate, Date createDate,
			String schoolCode) {
		this.answerFormNum = answerFormNum;
		this.questionSeq = questionSeq;
		this.markValue = markValue;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.schoolCode = schoolCode;
	}

	public Integer getAnswerSeq() {
		return this.answerSeq;
	}

	public void setAnswerSeq(Integer answerSeq) {
		this.answerSeq = answerSeq;
	}

	public String getAnswerFormNum() {
		return this.answerFormNum;
	}

	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	public String getMarkValue() {
		return this.markValue;
	}

	public void setMarkValue(String markValue) {
		this.markValue = markValue;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

}
