
package com.saiten.model;
/**
 * TranScorePercentageId generated by hbm2java
 */
public class TranScorePercentageId implements java.io.Serializable {

	private String answerFormNum;
	private String subjectCode;

	public TranScorePercentageId() {
	}

	public TranScorePercentageId(String answerFormNum, String subjectCode) {
		this.answerFormNum = answerFormNum;
		this.subjectCode = subjectCode;
	}

	public String getAnswerFormNum() {
		return this.answerFormNum;
	}

	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TranScorePercentageId))
			return false;
		TranScorePercentageId castOther = (TranScorePercentageId) other;

		return ((this.getAnswerFormNum() == castOther.getAnswerFormNum())
				|| (this.getAnswerFormNum() != null && castOther.getAnswerFormNum() != null
						&& this.getAnswerFormNum().equals(castOther.getAnswerFormNum())))
				&& ((this.getSubjectCode() == castOther.getSubjectCode())
						|| (this.getSubjectCode() != null && castOther.getSubjectCode() != null
								&& this.getSubjectCode().equals(castOther.getSubjectCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnswerFormNum() == null ? 0 : this.getAnswerFormNum().hashCode());
		result = 37 * result + (getSubjectCode() == null ? 0 : this.getSubjectCode().hashCode());
		return result;
	}

}
