package com.saiten.model;

// Generated Jul 1, 2014 11:56:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TranQualitycheckScore generated by hbm2java
 */
@SuppressWarnings("serial")
public class TranQualitycheckScore implements java.io.Serializable {

	private Integer qcSeq;
	private TranDescScore tranDescScore;
	private Integer questionSeq;
	private String scorerId;
	private Integer gradeSeq;
	private Integer gradeNum;
	private Double bitValue;
	private Integer pendingCategorySeq;
	private Short pendingCategory;
	private Character validFlag;
	private Character refFlag;
	private Date updateDate;
	private Date createDate;
	private Short scoringState;
	private String scorerComment;
	private String answerFormNum;

	public TranQualitycheckScore() {
	}

	public TranQualitycheckScore(TranDescScore tranDescScore, String scorerId) {
		this.tranDescScore = tranDescScore;
		this.scorerId = scorerId;
	}

	public TranQualitycheckScore(TranDescScore tranDescScore,
			Integer questionSeq, String scorerId, Integer gradeSeq,
			Integer gradeNum, Double bitValue, Integer pendingCategorySeq,
			Short pendingCategory, Character validFlag, Character refFlag,
			Date updateDate, Date createDate, Short scoringState,
			String scorerComment, String answerFormNum) {
		this.tranDescScore = tranDescScore;
		this.questionSeq = questionSeq;
		this.scorerId = scorerId;
		this.gradeSeq = gradeSeq;
		this.gradeNum = gradeNum;
		this.bitValue = bitValue;
		this.pendingCategorySeq = pendingCategorySeq;
		this.pendingCategory = pendingCategory;
		this.validFlag = validFlag;
		this.refFlag = refFlag;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.scoringState = scoringState;
		this.scorerComment = scorerComment;
		this.answerFormNum = answerFormNum;
	}

	public Integer getQcSeq() {
		return this.qcSeq;
	}

	public void setQcSeq(Integer qcSeq) {
		this.qcSeq = qcSeq;
	}

	public TranDescScore getTranDescScore() {
		return this.tranDescScore;
	}

	public void setTranDescScore(TranDescScore tranDescScore) {
		this.tranDescScore = tranDescScore;
	}

	public Integer getQuestionSeq() {
		return this.questionSeq;
	}

	public void setQuestionSeq(Integer questionSeq) {
		this.questionSeq = questionSeq;
	}

	public String getScorerId() {
		return this.scorerId;
	}

	public void setScorerId(String scorerId) {
		this.scorerId = scorerId;
	}

	public Integer getGradeSeq() {
		return this.gradeSeq;
	}

	public void setGradeSeq(Integer gradeSeq) {
		this.gradeSeq = gradeSeq;
	}

	public Double getBitValue() {
		return this.bitValue;
	}

	public void setBitValue(Double bitValue) {
		this.bitValue = bitValue;
	}

	public Integer getPendingCategorySeq() {
		return this.pendingCategorySeq;
	}

	public void setPendingCategorySeq(Integer pendingCategorySeq) {
		this.pendingCategorySeq = pendingCategorySeq;
	}

	public Character getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(Character validFlag) {
		this.validFlag = validFlag;
	}

	public Character getRefFlag() {
		return this.refFlag;
	}

	public void setRefFlag(Character refFlag) {
		this.refFlag = refFlag;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return the scoringState
	 */
	public Short getScoringState() {
		return scoringState;
	}

	/**
	 * @param scoringState
	 *            the scoringState to set
	 */
	public void setScoringState(Short scoringState) {
		this.scoringState = scoringState;
	}

	/**
	 * @return the scorerComment
	 */
	public String getScorerComment() {
		return scorerComment;
	}

	/**
	 * @param scorerComment
	 *            the scorerComment to set
	 */
	public void setScorerComment(String scorerComment) {
		this.scorerComment = scorerComment;
	}

	/**
	 * @return the answerFormNum
	 */
	public String getAnswerFormNum() {
		return answerFormNum;
	}

	/**
	 * @param answerFormNum
	 *            the answerFormNum to set
	 */
	public void setAnswerFormNum(String answerFormNum) {
		this.answerFormNum = answerFormNum;
	}

	public Integer getGradeNum() {
		return gradeNum;
	}

	public void setGradeNum(Integer gradeNum) {
		this.gradeNum = gradeNum;
	}

	public Short getPendingCategory() {
		return pendingCategory;
	}

	public void setPendingCategory(Short pendingCategory) {
		this.pendingCategory = pendingCategory;
	}

}
